
import type { BloggerPersona, BloggerTemplate } from '@/types/blogger';

export const REFERENCE_PERSONAS: BloggerPersona[] = [
    {
        id: '1',
        name: "Harriet Harry Greene",
        role: "Lifestyle Columnist",
        bio: "Lifestyle columnist with 16+ years capturing the heart of British food culture",
        expertise: "British traditions, nostalgic storytelling, rural-to-urban food journeys",
        avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Harriet",
        tone: "Nostalgic, Warm, Storytelling",
        writing_style: "Narrative-driven, cultural",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: '2',
        name: "Alistair Malik",
        role: "B2B Copywriter",
        bio: "B2B copywriter with 20 years of experience in e-commerce logistics and supply chain communication",
        expertise: "Cross-border shipping, procurement, logistics cost optimization",
        avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alistair",
        tone: "Professional, Analytical, Direct",
        writing_style: "Business-focused, technical",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: '3',
        name: "Priya Moore",
        role: "Food Writer",
        bio: "Writer with 15+ years exploring multicultural British cuisine and diaspora flavor blending",
        expertise: "Cross-cultural food writing, diaspora recipes, fusion cooking",
        avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Priya",
        tone: "Cultural, Exploratory, Inclusive",
        writing_style: "Descriptive, fusion-focused",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: '4',
        name: "Lola Adeyemi",
        role: "Digital Marketer",
        bio: "London-based digital marketer with 16+ years leading SEO-driven content strategies for e-commerce brands",
        expertise: "SEO content marketing, keyword optimization, SERP strategy",
        avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lola",
        tone: "Strategic, Persuasive, SEO-optimized",
        writing_style: "Marketing-driven, actionable",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: '5',
        name: "Nathan White",
        role: "Investigative Journalist",
        bio: "Investigative journalist with 17+ years analyzing UK consumer behavior, ethical sourcing, and sustainability issues",
        expertise: "Consumer activism, retail ethics, deep supply chain analysis",
        avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Nathan",
        tone: "Investigative, Critical, Ethical",
        writing_style: "Journalistic, fact-based",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: '6',
        name: "Dr. Emily Francis",
        role: "Health & Wellness Writer",
        bio: "Health and wellness writer with a Ph.D. in Nutrition Science and 17+ years bridging scientific research with consumer-friendly health writing",
        expertise: "Nutritional science, diet-specific writing, allergen management, child nutrition",
        avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Emily",
        tone: "Scientific, Authoritative, Accessible",
        writing_style: "Evidence-based, educational",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    }
];

export const REFERENCE_TEMPLATES: BloggerTemplate[] = [
    {
        id: '1',
        name: "How-to Post",
        description: "A step-by-step guide to help readers achieve a specific goal.",
        content_structure: "Intro (Who is this for & Why it matters); H2: Tools and Materials You'll Need; H2–H3: Step-by-Step Instructions (Step 1–N); H2: Expert Tips, Common Pitfalls & Warnings; H2: Final Thoughts and Encouragement to Try It Now",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: '2',
        name: "List Post",
        description: "A curated list of items, tips, or resources.",
        content_structure: "Intro (Hook + Who it's for); H2–H3: List Items with Rich Descriptions, Real Use Cases, Pros & Cons, Internal Links; H2: How to Select the Best Option for Your Needs; H2: Explore More and Final Recommendations",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: '3',
        name: "Beginner's Guide",
        description: "A comprehensive introduction to a topic for beginners.",
        content_structure: "Intro (Context + Purpose); H2: What Is {{primary_keyword}} and Why It's Important; H2: The Core Concepts Every Beginner Must Know; H2: Getting Started with Confidence (Steps, Tools, Resources); H2: Frequently Asked Questions (Max 6 Questions, Answered Clearly); H2: Wrapping Up with Your First Steps Forward",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: '4',
        name: "Review Post",
        description: "An in-depth review of a product or service.",
        content_structure: "Intro (Your Credentials + Review Purpose); H2: In-Depth Product Overview and Technical Specs; H2: Pros, Cons, and User Experience; H2: Real-World Testing Results and Analysis; H2: Comparing with Alternatives in the Market; H2: Final Verdict: Who Should Buy This?",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: '5',
        name: "Statistics / Data-Focused Post",
        description: "A data-driven post with charts, graphs, and analysis.",
        content_structure: "Intro (Why This Data Matters Now); H2: Key Trends & Surprising Findings You Should Know; H2: Easy-to-Read Charts, Graphs, and Raw Tables; H2: What the Data Tells Us (Detailed Analysis); H2: Implications for {{industry or audience}}; H2: Final Takeaways and Downloadable Report",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: '6',
        name: "Response Post",
        description: "An expert response to a trending topic or query.",
        content_structure: "Intro (Who You Are + Context); H2: What Was Said and Why It Matters; H2: Critical Breakdown and Response with Evidence; H2: Fact-Based Clarifications & Supportive Data; H2: Final Thoughts on the Issue",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: '7',
        name: "Ultimate Guide / Comprehensive Post",
        description: "The definitive guide to a topic, covering everything.",
        content_structure: "Intro (Who You Are, Why This Guide Exists); H2: What Is {{primary_keyword}} and Why Is It Important?; H2: A Brief History and Industry Evolution; H2–H3: Subtopics and Strategic Insights (2–4 sections); H2: Best Practices, Tools & Frameworks You Can Use; H2: Frequently Asked Questions (Limit 6, Fully Answered); H2: Final Thoughts and Links to Further Learning",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: '8',
        name: "Case Study",
        description: "A real-world example of a problem and solution.",
        content_structure: "Intro (Set the Stage with Persona's Role); H2: The Challenge Faced and Its Context; H2: The Step-by-Step Solution We Implemented; H2: Key Results and Measurable Impact (Use Data); H2: Lessons We Learned That Others Can Use; H2: What's Next and Where to Go From Here",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: '9',
        name: "Comparison Post",
        description: "A side-by-side comparison of multiple options.",
        content_structure: "Intro (Why Compare These Options + Persona Intro); H2–H3: Comparison of Each Option (Description, Pros, Cons, Use Case, Link); H2: How to Make the Right Choice for Your Needs; H2: Final Verdict and Recommendations",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    }
];
