-- Add faqs column to pending_products table
-- Stores FAQ data as JSONB array: [{"question": "...", "answer": "..."}, ...]

ALTER TABLE pending_products
ADD COLUMN IF NOT EXISTS faqs JSONB DEFAULT NULL;

COMMENT ON COLUMN pending_products.faqs IS 'FAQ data generated by the FAQ agent. Array of {question, answer} objects.';
